### ISSUE TITLE
Ban Appeal: utw

### ISSUE THREAD

**Issue by rxycz** [Kyrobi/Cynagen#106]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: utw

**I was banned on**: 13th July 2019

**I was banned by**: Unknown

**I was banned for**: Typing the nword on a sign.

**A brief summary of what happened before the ban was**: I was testing coloured signs and the first word i thought of was the nword, yes it was stupid but i didnt think it would get me banned as i was going to break it after testing the colours. 

**I like to be unbanned because**: What i did was wrong, but i believe it wasnt ban worthy. i also have a new pc and am wanting to play on cynagen again. i hope you understand.

**What's wrong with you?**: uhhh im not retarded i swear.... jokes what does this mean?...

**Additional information**: (Optional)

**Comment by Kyrobi** [comment]
Before you got banned from the server, you've expressed in chat many times that you were going to leave the server for good. This included selling off your pigmen farm and some of your other loots.

You know full well that saying the N word in any capacity will get you banned; yet, you still decided to test it anyways. You typed the N word on the server day that you claim was your "last" day on the server. This lead me to believe that saying the N word was how you wanted to exit the server.

Furthermore, you did not really even bother to appeal or message the server when you got banned. And then out of nowhere (189 days later), you decided to appeal.

This makes me think that you purposely caused the issues above and are only trying to appeal now since it's convenient for you. What are your inputs on this?

**Comment by rxycz** [comment]
I simply was quitting mine craft as my laptop had become a piece of crap
and barely worked anymore. never really expected to get a pc but here i am
with a pc. Yes i was quitting but no i did not purposely say the nword on a
sign to purposely get into trouble or get banned or anything.

**Comment by Kyrobi** [comment]
That's fair. Just note that if you are to use any slurs, it will be instantly banned with no chance to appeal. Why? You already have a bad history on the server:

![image](https://user-images.githubusercontent.com/20980266/72676215-62f35700-3a54-11ea-832a-b592d5c3c087.png)

Your ban will expire in 12 hours. While you wait for your ban to expire, please carefully read over the rules: https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md so there's no excuse for being banned again. A lot has changed since you were banned.

**Comment by rxycz** [comment]
read all the rules. thankyou for being understanding. see you in 12 hours
