### ISSUE TITLE
Ban Appeal: 

### ISSUE THREAD

**Issue by ryley8979** [Kyrobi/Cynagen#123]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: ANDOVEA

**I was banned on**: (Format: Dec 23, 2012) Jan 22, 2020

**I was banned by**: (Leave blank if unknown) Succubi_Snow

**I was banned for**: Greifing

**A brief summary of what happened before the ban was**: i havent played minecraft since 2019 so i dont know why i was banned

**I like to be unbanned because**: i wasnt online, i wasnt on the server and i dont have any hacking things on my laptop

**What's your opinion on getting tattoos?**: tattoos are epic

**Additional information**: (Optional)

**Comment by joshuag1000** [comment]
To be clear I am NOT a moderator and i have no say in your ban appeal.
You appear to have logged into this server 3 times in 2020. If this was not you in any way (which for all i know i might) you might want to consider changing your minecraft password and security settings.
![image](https://user-images.githubusercontent.com/28513051/75278447-cade4f80-5801-11ea-8bb9-531e07bbe9a8.png)

**Comment by ToxicSnow** [comment]
I'll be honest, I don't even remember what was griefed, nor can i find screenshots or logs of the incident as it was before we started logging everything, As this was your first offence and bc i saw that the last time you had been on was 17 days before it was reported I figured that a perm ban would get a better response than a week ban that you wouldn't have been aware of. so now that that's cleared up, you are now unbanned but you still might want to change your password if you haven't been on since the 25th of December as someone was on your account and they did grief if that wasn't you.

**Comment by Kyrobi** [comment]
Just a note:

You are responsible for anything that the account does and securing your account.
