### ISSUE TITLE
Ban Appeal: Jmk555

### ISSUE THREAD

**Issue by 44h-wq** [Kyrobi/Cynagen#150]
Please title this post "Ban Appeal:" followed by a name

**Minecraft username**:
jmk555
**I was banned on**: (Format: Dec 23, 2012)
april 8th 2020
**I was banned by**: (Leave blank if unknown)
Sccubi_Snow
**I was banned for**:
griefing
**A brief summary of what happened before the ban was**:
I actually dont know. I was claiming places on the map when me and two other players that had not done anything were all kicked for griefing. Our other friends were taking things from houses that weren't claimed earlier, but I wasn't involved, and I was just walking through a Forrest when it happened.
**I like to be unbanned because**:
because I feel like I didn't do anything wrong, and I like having fun with my friends. Only a couple people we didnt know that well were griefing, and that was it.
**Explain why is cereal is/isn't considered a soup**:
Because milk can be mixed in soup, but it is illegal to call cereal a soup, especially because it is typically sweet.
**Additional information**: (Optional)

**Comment by ColtCrohnie** [comment]
If you and your friends read the rules you would know that regardless of whether a build is claimed or not, griefing is not allowed. Also there are places where you and your friends griefed multiple times (I know you griefed as well because I checked the logs) So when you say you didn't grief it kinda makes me chuckle.

**Comment by 44h-wq** [comment]
Well man, I didn’t know you couldn’t take things from houses that weren’t claimed so I’m sorry about that. But why was 
Aiden’sworld and cop3rnicus banned? They were farming the whole time. And at that house that was getting grieved and destroyed, my friend just told me to TP there and than I looked in the chest and didn’t take anything. But I’m sorry overall.

**Comment by 44h-wq** [comment]
Man, can you just unban us. We won’t do it again.

**Comment by 44h-wq** [comment]
Did you guys destroy our farm?

**Comment by ColtCrohnie** [comment]
No? We're not griefers unlike your friends.

**Comment by 44h-wq** [comment]
Dude, that one house Where the windows were destroyed, I think the only thing I broke was a flower pot. And I thought the place was a Abandoned. Like I’m not even sure there was a door on the house. I went inside and I opened the chest because there were seven people in there. There were only seeds and flowers and stuff like that. And then I just hung out there for a minute and than left. But why were Aiden’sworld and Cop3rnicus banned? They were just farming the whole time.

**Comment by ColtCrohnie** [comment]
Claimed or not Griefing is against the rules, it's literally the first rule, so I don't feel bad for you getting banned because you were ignorant of the rules. Also you broke more than just a flower pot don't try to play that game with me because I checked your logs and block history before I banned you. We ended up banning everyone in your little party because most of them griefed and others were with them, those who didn't grief just need to file a ban appeal. 

Your ban appeal has been denied, please take the time to read the rules thoroughly before returning. Your ban expires in 12 days.

https://github.com/Kyrobi/Cynagen/blob/master/Files/Rules.md

**Comment by 44h-wq** [comment]
Plus, I wasn’t trying to grief anything, I just thought that houses that were clearly abandon were up for grabs, even though I didn’t take anything.

**Comment by 44h-wq** [comment]
That thing with the house and the windows being destroyed happened before I was walking through the forest.

**Comment by 44h-wq** [comment]
What was my Block history?

**Comment by ColtCrohnie** [comment]
Your block history revealed that you removed bookshelves, windows, flower pots and building blocks as well as took items from chests from the exact same locations you and your friends were raiding.

**Comment by 44h-wq** [comment]
But I only destroyed the flower pot?

**Comment by 44h-wq** [comment]
Ok, your lying right now, or you’re not being honest. Because At the absolute most I broke one window and the flower pot.  I don’t even remember breaking one window. I didn’t take anything from the chest, because there was nothing to take, it was just seeds and pieces of stone. Plus there was already 3 to 4 players there, so everything was picked clean. I didn’t destroy building materials I didn’t take any bookshelves, and I sure as hell didn’t take anything from the chest. Plus when we made our enchantment table we had all the bookshelves we needed so there would be no point in doing that.
