### ISSUE TITLE
Player Report: 

### ISSUE THREAD

**Issue by GriffonDragon** [Kyrobi/Cynagen#23]
Please title this post: "Player Report:" followed by a name.

Report Template:
####################

**My Minecraft username**:
Blue_Phoenix23 
**I am reporting**:
Saiyku™ ~#0989 aka VulcanGamerHD
**I'm reporting this person for**:
Harassment in chat on discord
**Screenshot or video link if available**:
Dm me at gaudoo#7268
**Additional information**: (Optional)
This user harrassed me on discord after reading a player report against me saying "why do you have to make yourself so unlikable" and continued even after i told the user to drop the conversation.

**Comment by Saiyku** [comment]
Alright so lemme make this clear for all the people that are going to read this. 
1. Blue has no respect for other players by continuing to talk about a sensitive topic when others wanted to stop.
2. This event that Blue is talking about happened months and months ago, but is here again talking about it when no one asked.
3. Yes, I did ask her, "why do you have to make yourself so unlikable," because, well, she is doing exactly that. If people do not want me to talk about something, I, like any normal human, would stop and not talk about it. However, she wishes to keep blahing, thus making her unlikable. 
4. I have no idea how this is considered harassment. Here is the whole screenshot: 
![image](https://user-images.githubusercontent.com/49375191/57672070-8c660400-75e4-11e9-8069-938f17308007.png)
5. Stop hating people for telling the truth. Life sucks, but we are all here moving forward.

**Comment by GriffonDragon** [comment]
I haven't talked to Colt about ANY controversial topics in the last month. 
What's in the past is behind us, I've changed. 
Yes, in my past I was toxic, now, I am not, and I vow this. 

And yet, you are continuing to harrass me even on this thread. What's done is in the past, and you aren't letting me leave it behind.

Please stop attacking me, and see just how I've changed.

**Comment by Saiyku** [comment]
1. I doubt you know what "harass" actually means. Here's the definition for you: 
![image](https://user-images.githubusercontent.com/49375191/57672326-aeac5180-75e5-11e9-8e1c-9237839e9f44.png) "repeated" doesn't mean 2-3 times like what I did.
2. No, you obviously haven't changed.

**Comment by Kyrobi** [comment]
That moment when no one can grow up and just don't give a crap at all. I doubt Saiyku would randomly confront you about this. What did you do this time?

**Comment by GriffonDragon** [comment]
I randomly recieved a player report against me, of which I don't understand why, when i didn't do anything controversial since that one message you told me about. Yet the damage was already done, and even when i tried to make things right, people holding grudges (que the incident).
So these so and so "reports" are old, They HAVE to be. And thus i was kicked from the discord of which I believe was a bit much of a punishment. I may slip up here and there, but I am actively trying to improve. 

I do feel as if Saikyu's messages were uncalled for and that a Staff should have talked to me about the issue to solve this properly. Feel free to DM me at anytime to discuss further.

**Comment by Kyrobi** [comment]
I don't want to discuss this issue any further. I also don't want anyone else bringing up this subject. You guys should all try to act like adults.
