### ISSUE TITLE
Ban Appeal: vexxist

### ISSUE THREAD

**Issue by vexxist** [Kyrobi/Cynagen#269]
Please title this post "Ban Appeal:" followed by your username.

### Please fill in the information below

**Minecraft username**:
vexxist
**I was banned for**:
being immature, not being too great of a person all around to everyone
**A brief summary of what happened before the ban was**:
i can't really remember, but as i said, i was being pretty awful for the community
**Why is what you got banned for bad?**:
personally i wouldn't want someone to behave like that around me
**I like to be unbanned because**:
it's been a while since my last appeal, and i understand why that one was denied, but it's been a while since then and i promise i'm not a goober anymore. i really want a mc server to play occasionally, and every other server isn't like this one. 
**Reflect on what you did wrong. What are some things you will start doing to improve yourself?**:
well i've been becoming a different person, not to get into too much detail about my personal life, but i truly regret the person i used to be. even then i didn't like myself. but now im in therapy! and i need a hobby, or something to do in my freetime.
**Explain why and when the best time to mow the lawn is**:
later in the afternoon. everyone should be awake, and it's not as hot out
**Additional information**: (Optional)
thank you for reading

**Comment by JokerBoss99** [comment]
You are right on this server not being like any other one. You had multiple chances leading up to your first permaban, and I gave ya a second chance since you seemed pretty sincere about your appeal. During the time when you were unbanned, there was relentless drama (you were at fault, and so were others). However since you’ve been banned all the related drama has gone away, and I don’t see why I would want to make that mistake again. I’m glad and proud of you for going into therapy since it’s a very valuable tool, but I’d suggest looking elsewhere for an outlet for hobbies. 

Try again in a couple years or sum

**Comment by vexxist** [comment]
thank you Mr. joker boss99

**Comment by oktead** [comment]
free vex
