### ISSUE TITLE
Ban Appeal: Kyrobi

### ISSUE THREAD

**Issue by Kyrobi** [Kyrobi/Cynagen#37]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: Kyrobi

**I was banned on**: 7/14/2019

**I was banned by**: ColtCrohnie

**I was banned for**: Advertising

**A brief summary of what happened before the ban was**: ColtCrohnie was being mean to me. So to spite him, I decided to advertise my factions server.

**I like to be unbanned because**: I like the server

**I often slap little kids because**: I like it

**Additional information**: (Optional)

**Comment by ColtCrohnie** [comment]
Dear User,

We regret to inform you that after reviewing your ban appeal that we will not be removing your ban from the server.

Despite the fact that no staff member or player were harassing you, no motive or explanation will justify actively advertising for a server other than our own.

Feel free to go play on the server you advertised because you will not be welcome here any longer.

Sincerely,
ColtCrohnie
Moderator of Cynagen
