### ISSUE TITLE
Ban Appeal: EpicBammer

### ISSUE THREAD

**Issue by TheEpicBammer** [Kyrobi/Cynagen#39]
Note: All the issues made here are public, meaning everyone can see it.
If you would instead like to make a private issue or have a private discussion, you can type **-new** on the Discord server to create a private chat with the staff.
You might also get faster response time.

Please title this post "Ban Appeal:" followed by a name

**Minecraft username**: EpicBammer

**I was banned on**: 21/7/2019

**I was banned by**: Kyrobi

**I was banned for**: X-ray

**A brief summary of what happened before the ban was**: I was x-raying

**I like to be unbanned because**: I really liked playing on the server and talking to the community and frankly just didn't think that x-ray was a bannable offense. 

**I often slap little kids because**: It's oddly satisfying?..

**Additional information**: I'm willing to give up my diamonds and stuff and of course not x-ray again, and I know you'll be able to see if I do it again so there would be no point in trying. would really appreciate it

**Comment by Kyrobi** [comment]
I am actually disappointed by the fact that you thought X-ray wasn't a bannable offense. Did you even read the rules? There's only 6 of them.
 You kinda of broke two rules at once: Do not hack and use common sense.

Since you gotten out of your way to make this ban appeal and are willing to change your ways, you'll be given another chance.

**Comment by TheEpicBammer** [comment]
Really apprectiate it man, didn't read the rules but I will when I rejoin. You won't regret it!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
