### ISSUE TITLE
Bug: Cats suffocating while in minecarts

### ISSUE THREAD

**Issue by TachankaLord** [Kyrobi/Cynagen#51]
**Minecraft username**: __LordTachanka__

**Expected behavior**: When placed in a minecart surrounded by trapdoors cats should just sit there and do nothing.

**Actual behavior**: When placed in a minecart surrounded by trapdoors cats will randomly suffocate in a wall and the minecart will disappear.

**How can this issue be replicated?**: Place a cat in a minecart on a flat surface and surround it with trapdoors that are flat on the floor (see screenshot).

**A screenshot / video link if available**:
![2019-08-01_22 14 38](https://user-images.githubusercontent.com/53581946/62324812-8fb5b100-b4aa-11e9-8384-32d0f39712fe.png)

**Additional information**: Don't know if this happens when the cat is not surrounded by trapdoors but I have already wasted enough minecarts and cats. Both times this happened it happened to all of the cats at once and I was on the ground while the cats where at about y=200.

**Comment by Kyrobi** [comment]
Hello. I've tried to recreate what you've described to no success. 

Video: https://youtu.be/d4AbXZYfdmw

**Comment by TachankaLord** [comment]
Both times this happened it was not instant the first time took 20 minutes and second time more like 5. And like I said I was quite far away when it happened.

**Comment by Kyrobi** [comment]
You didn't mention in your original post that you were far away from your cat when it happened. I will do some further testing later.

**Comment by Kyrobi** [comment]
So I've done more testing; it appears to be a Minecraft issue rather than.

Testing methods:

1. Testing it with a clone of the main server but it no plugins. Cats died.
2. Testing it inside a single player world. Cats died.


![image](https://user-images.githubusercontent.com/20980266/63072118-bd0d5080-bee7-11e9-9a0c-dd957d298793.png)


Seems like an issue that's ultimately left up to Mojang to fix.
