### ISSUE TITLE
Ban Appeal: snail6_booyah

### ISSUE THREAD

**Issue by Snail667** [Kyrobi/Cynagen#55]
**snail6_booyah**:

**8/16/2019**: (date)

**Being wrongly accused of griefing a shop**: (Leave blank if unknown)

**Killing someone**:

**He killed my dog because he randomly attacked me and I got angry, so I killed him, a moderator saw, and now I'm banned for 5 days 😭**:

**I love this server**:

**I really love this server and someone told everyone to steal my stuff and I need to stop them fast. I DIDN'T GRIEF HIS SHOP**: (Optional)

**Comment by lovingminecraft321** [comment]
I know this kid he goes to my camp  and when he got banned he was like "i HATE THAT MOD" he is not saying the full story before the dog killing he was hitting people that are in the server in real life he was griefing shops, he stole from people in the servers, example, he stole a few diamonds from my friend to make himself a helmet. He was given perms since you could claim land in this server. He was told not to grief or steal for obvious reasons. I am writing this because I would just like you to consider these facts. But otherwise I love your server. Thanks.

**Comment by Snail667** [comment]
THAT IS A LIE I DID NOT SAY I HATE THAT MOD HES LYING TO GET ME IN MORE TROUBLE HE KEEPS SAYING THAT I DONT DESERVE TO BE BACK IN THE SERVER HE'S BEEN HARRASING ME SINCE DAY 1 AND I HAVE NEVER DONE ANYTHING TO HIM! HES SUCH A BULLY. I LOVED THAT DOG!

**Comment by Snail667** [comment]
OK I was thinking about it and we came to the conclusion I was mining I accidentally broke it and im very sorry please shorten my sentence, and I didn't say "I HATE THAT MOD", just btw that was a lie.
