### ISSUE TITLE
Ban Appeal: TrollGorilla

### ISSUE THREAD

**Issue by TrollGorilla** [Kyrobi/Cynagen#56]
**Minecraft Username**: TrollGorilla28

**I was banned on**: August 23, 2019

**I was banned by**: ColtChronie

**I was banned for**: X-Ray

**A brief summary of what happened before the ban was**: I was strip mining and when I asked for a mod's help. After he answered my question he began to look around where I was. I had 50 gold from when I was mining, and he accused me of X-Ray. I tried to explain that i wasn't using X-Ray, but my internet went out. When it came back and tried to join the server, I was met with a message that said I was banned from the server, even though I was falsely accused.

**I like to be unbanned because**: I love playing on this server and I didn't do anything wrong. I genuinely tried to respond but my internet went out, and I wasn't able to explain I didn't do anything wrong.

**I Like slapping little kids because**: Why not?

**Additional information**: I have never used a hacked client and I never will.

**Comment by Kyrobi** [comment]
Seems like a lot of hacker's internet magically goes out when confronted. Dang, I should look into that mystical powers this server might have.

The imaged attached, there's no other diamond ore within 20 blocks radius from here. You magically mined straight down to it.

![xray1](https://user-images.githubusercontent.com/20980266/63630294-d052a700-c5de-11e9-8d11-d3fa9223a603.png)

Would you like to explain this? I don't appreciate people who try to appeal and also lie on it.

**Comment by TrollGorilla** [comment]
I guess I just got lucky, I was looking for an end portal and i mined down to mine towards it. I know it seems highly unlikely, but things can happen by chance also. I know it seems suspicious, but please trust me on this. I really enjoy playing on Cynagen and I have never used a hacked client. I've been having trouble with internet the past few days, and there was a service technician working while I was on the server.

**Comment by VulcanGamersHD** [comment]
Alright man, your story is obvious a lie and anyone can tell. Are you seriously going to say that you are looking for an end portal at bedrock level? Strong holds doesn't even have room to spawn.

Just be honest and admit to xray. Then ask nicely for an unban.

**Comment by ToxicSnow** [comment]
You had no eyes of ender on you, for one, Secondly, The shaft that goes down stops at y=47 where those diamonds weren't anywhere close to the shaft dug, you went around until you found a tunnel that was dug out then went straight for the diamonds. As far as things in your inventory you also had 72 diamonds in there, Why wasnt that included in your little story or was it too incriminating that you decided to leave it out of your work of fiction

**Comment by TrollGorilla** [comment]
I think there might have been a mix-up. In my inventory I only 4 diamonds and I had 12 eyes of ender. If you allow me back on you will never see anything of me X-Raying, because I haven't downloaded anything. And if you don't, for the time I played on Cynagen, I had a load of fun.

**Comment by ColtCrohnie** [comment]
I took 72 diamonds straight out of your inventory

**Comment by VulcanGamersHD** [comment]
Sir, your story feels crazier than the guy who said that his sister said the nword when he went to use the restroom. It's already a bad impression to hack on the server, but it's another thing if you have to keep lying and denying it with such stupid excuses, I don't think you deserve to get an unban.

Do you really think the staffs are dumb? Come on man. First you said that you were just strip mining, but Kyrobi shows us a picture of you just "randomly" digging down to 

> find an end portal.

 Somehow, by mere "luck," you end up finding the only diamonds in a 20 block radius? Now back to the end portal in which you said you were looking for... at y 5??? Reallyyyy? I know it is hard to find an end portal, but its not impossible. However, with your intelligence, I think you might never find one. I mean, have you ever even seen how big the damn thing is? There is no room for any end portals to spawn after like y15-30 I believe. 

We are just going to skip the 72 diamonds part because there's no point since you will just deny it.

So, finally, you said you would 

> allow me back on you will never see anything of me X-Raying, because I haven't downloaded anything.

I don't think anyone could be this stupid. But naw, people like you always prove me wrong. Anyone can know that you can just delete any xray hack or texturepack before you join back in. Come on man, use your brain and think. 

Read my last reply. Admit that you have xrayed and just ask nicely for an unban. There is no shame in admitting your wrongs and starting over, everyone have second chances. But, there are lots of shame in lying like an idiot.

**Comment by Kyrobi** [comment]
If you truly believe that you have done nothing wrong and all of this is just a mistake, we can arrange a screenshare session. 

Feel free to join our Discord server at https://discordapp.com/invite/B5JW7qp.

If you don't have a Discord account, create one with a username name matching your In-game name. If you already have an account, temporarily change your username to your in-game name so that we can easily tell which one is you.

**Comment by Kyrobi** [comment]
Further investigation shows that there's no concrete evidence of you hacking besides that photo. You are unbanned.
