### ISSUE TITLE
I've been banned for 2 days!

### ISSUE THREAD

**Issue by IceKebab** [Kyrobi/Cynagen#90]
Basically, another player in the server decided to buy some shulkers from me and he owed me 15 bc he was 15 short becasue he bought 11 shulkers alright so after he bought them he tpa'ed to me and jokingly gave me a piece of paper named I O U 15 and he was basically trying to get around not paying it lmao. So anyway i was in the end searching for some end city's and what not and he tpa'ed me and I got pissed I have a short temper so iIwas punching him with my fists and before he logged out he dropped his stuff but he wasnt on low health so i guess that was part of the glitch in the end. Anyway i didn't give him his stuff back and the next day he reported me and Joker banned me.  Also  would like to add joker is out to get me idk why he has a problem with me. -_-

**Comment by JokerBoss99** [comment]
No, what you did do was scam another person, and TP kill them.
If you would like to re-appeal with the correct format, feel free to do so. Also, if the issue is that the ban is only two days, I could extend that if you would like! Just let me know!

**Comment by IceKebab** [comment]
I was in the end. Okay this person came a did a joke because i lost my elytra i did not plant to TP kill them and i did not intend to scam.

**Comment by IceKebab** [comment]
I was in the end to find an Elytra and I didn't intend to kill them. I hardly did any damage I was merely using my fist I didn't use a weapon and I didn't plan to TP kill him, I was merely joking and when he logged out as the end is glitchy he lost his stuff he was wearing diamond armor he couldn't have died from me using my hand in-game and we were in the end and the end is glitchy so when he logged out It dropped his things. I did not TP kill him I did not say I wasn't going to give his stuff back. As well as not implying for a longer ban time.

**Comment by ToxicSnow** [comment]
So I will fill in where joker missed a statement of how the server works, once PVP is engaged on the server it starts a combat log that lasts until 30 seconds after blows stop being traded, if during that time one of the players disconnects all of their items if not in the overworld are dropped, as for not being able to kill him because of him being in armor, that is false bc it is entirely possible on this server to kill someone with a fist, Unarmed, a skill from mcmmo, allows a player to deal as much damage as a full enchant diamond sword, with said fist. as for being 15 dollars short, him handing you a slip of paper was his way of giving u something to track the transaction and let him vote/do something to get the money to you at a later date. Instead you, took this as him getting around the payment of 15 measly dollars of a from what I can tell was a much larger amount of cash that he at the time did not have. Which in my professional opinion, is more than most on the server can attest to doing. Now generally when doing a bulk purchase, the one buying the item either has a lot of the item and just wants more as is the case for most of the server, or either doesn't have any of the item and was looking for a better deal with the cash on hand. In this particular instance I think it was the latter, however he was short by 15, so he did the one thing he thought was nice, giving you an IOU for the amount owed.

**Comment by Kyrobi** [comment]
I guess it's also Doggo's logging out of the game that made the issue seem worse than it did. Since Doggo didn't know that PvP tagging was a thing, it killed him instantly when he logged. 

Despite your intention of never trying to kill him, he still died.
I will grant you a pardon only if you promise to give back all of the victim's lost items.

**Comment by Kyrobi** [comment]
I guess it's also Doggo's logging out of the game that made the issue seem worse than it did. Since Doggo didn't know that PvP tagging was a thing, it killed him instantly when he logged. 

Despite your intention of never trying to kill him, he still died.

Since there didn't seem to be ill intent (@ Kyrobi), I will grant you a pardon only if you promise to give back all of the victim's lost items.

**Comment by IceKebab** [comment]
Sure i don't mind giving back his things, but i didn't enable an mcmmo and i don't know how to enable an mcmmo with the fist or something like that, but i'll sureley give him his stuff back.

**Comment by IceKebab** [comment]
I really don't mind giving him his stuff back, and the mcmmo thing Idk how to enable it so... That's lost cause I would give him his stuff back I don't really want the pooper scooper shovel he had on him lmao. Btw I blocked joker on disc and i didn't add another admin so we couldn't really discuss this on a discord server, anyway thank you.
